name: pretender
description: >
  Pretender is a JavaScript mock server library useful for testing applications and Web Components built using
  Polymer Elements.
version: 0.2.0
author: Erik Grimes <erik.grimes@gmail.com>
homepage: https://github.com/nameitlater/pretender

environment:
    sdk: ">=1.8.0 <2.0.0"

dependencies:
  web_components: ^0.12.0
  js: ^0.6.0
  func: ^0.1.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
